language: node_js
node_js:
  - "v8.4.0"

services:
  - mysql

env:
  - DATABASE_URL= postgresql://localhost:5432/reg_numbers

before_install:
  - psql -c 'create database reg_numbers;' -U postgres
  - psql -U postgres -d reg_numbers -a -f tables.sql

addons:
  apt:
  packages:
  - postgresql-server-dev-9.2